server:
  port: 8082
  servlet:
    context-path: /ped
spring:
  application:
    name: ped
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pedido_produtos?useTimezone=true&serverTimezone=UTC
    username: root
    password: 
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5Dialect
        
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/registry/eureka

